"""Visual intelligence subsystem (world model, intent schema, asset registry, request routing)."""

from .assets import (
    AssetError,
    AssetFormat,
    AssetRecord,
    AssetRegistry,
    AssetStatus,
    AssetValidationError,
    DuplicateAssetError,
    UnknownAssetError,
    VerificationStatus,
    register_bundled_assets,
)
from .bridge import VisualBridge
from .concepts import (
    Concept,
    ConceptError,
    UnknownConceptError,
    VisualWorldError,
    load_concepts,
)
from .intent import (
    AnimationStyle,
    CameraPreset,
    EntityResolutionError,
    IntentAction,
    IntentMode,
    IntentValidationError,
    VisualIntent,
    resolve_entity_id,
)
from .routing import (
    SEARCH_GUARD_TOOLS,
    VisualRouter,
    VisualRouteResult,
    get_visual_router,
    last_user_utterance,
    route_search_request,
    route_visual_request,
)
from .world_model import (
    Entity,
    UnknownEntityError,
    UnknownPartError,
    VisualWorldModel,
)

__all__ = [
    "AnimationStyle",
    "AssetError",
    "AssetFormat",
    "AssetRecord",
    "AssetRegistry",
    "AssetStatus",
    "AssetValidationError",
    "CameraPreset",
    "Concept",
    "ConceptError",
    "DuplicateAssetError",
    "Entity",
    "EntityResolutionError",
    "IntentAction",
    "IntentMode",
    "IntentValidationError",
    "SEARCH_GUARD_TOOLS",
    "UnknownAssetError",
    "UnknownConceptError",
    "UnknownEntityError",
    "UnknownPartError",
    "VerificationStatus",
    "VisualIntent",
    "VisualRouteResult",
    "VisualRouter",
    "VisualBridge",
    "VisualWorldError",
    "VisualWorldModel",
    "get_visual_router",
    "last_user_utterance",
    "load_concepts",
    "register_bundled_assets",
    "resolve_entity_id",
    "route_search_request",
    "route_visual_request",
]
